import { LegalList, LegalPage, LegalSection } from "@/components/settings/legal-page";

export const metadata = {
  title: "What Elara does with your data — Elara AI",
  description:
    "Plainly: what is stored, what is sent elsewhere, what is never kept, and how to remove it.",
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy" updated="30 September 2026">
      <LegalSection heading="The short version">
        <p>
          Your voice is never stored. If you turn on conversation history, the
          <em> text</em> of your conversations is saved to your account. Everything
          else — your profile, your preferences — is stored so the app can work.
          You can delete all of it at any time.
        </p>
      </LegalSection>

      <LegalSection heading="Your audio is never stored">
        <p>
          Audio is captured only while a voice session is open, streamed to a
          speech-to-text provider, and discarded as it is transcribed. There is no
          recording feature, no voice history, and no audio column anywhere in the
          database. When you stop a session, the audio is gone.
        </p>
        <p>
          The one thing worth being precise about: that audio does travel to a
          third party to be transcribed. It is encrypted in transit, and it is not
          written to our storage — but the transcription provider processes it,
          and their own retention rules govern their copy. This is not end-to-end
          encryption: a service that transcribes your speech has to be able to
          hear it. We are telling you that plainly rather than implying a
          guarantee we cannot make.
        </p>
      </LegalSection>

      <LegalSection heading="Who processes your data">
        <LegalList>
          <li>
            <strong>Speech-to-text.</strong> Most languages are transcribed by a
            streaming speech service (AssemblyAI). Some languages — including
            Bengali — are transcribed by your own browser&apos;s built-in speech
            recognition instead, which means your browser vendor processes that
            audio, not us. Elara tells you in the app when it is using the browser
            engine.
          </li>
          <li>
            <strong>Replies.</strong> Answers are generated by hosted AI models run
            by third parties (Groq and Google AI Studio). Your conversation text is
            sent to them so they can produce a reply, and your conversation history
            is included so the reply can respond to what you just said.
          </li>
          <li>
            <strong>Web search.</strong> When a question needs current facts, a
            short search query is sent to a search provider (Bright Data). The
            query is derived from your question; your name and account details are
            not attached to it.
          </li>
          <li>
            <strong>Authentication.</strong> Email addresses, passwords and
            sessions are handled by Supabase. Passwords are hashed by them; we
            never see or store a plaintext password.
          </li>
        </LegalList>
      </LegalSection>

      <LegalSection heading="What is stored on your account">
        <LegalList>
          <li>Your email address, and your username and display name if you set them.</li>
          <li>Whether your account is a guest session.</li>
          <li>
            Your preferences: preferred language, speaking rate, theme, and
            whether conversation history is on.
          </li>
          <li>
            <strong>Only if history is on:</strong> the text of your conversations
            — what you said and what Elara replied. Capped at 500 turns per
            conversation.
          </li>
        </LegalList>
        <p>
          Turning history off in Settings stops new conversations being saved. It
          does not retroactively delete what is already stored, so delete the
          conversation if you want it gone.
        </p>
      </LegalSection>

      <LegalSection heading="What we never store">
        <LegalList>
          <li>Audio, in any form, at any point.</li>
          <li>Your password — it is hashed by Supabase and never reaches us.</li>
          <li>API keys or any other secret belonging to us, on your device.</li>
        </LegalList>
      </LegalSection>

      <LegalSection heading="Who can see your data">
        <p>
          Only you. Every table is protected by database-level row-level security:
          a signed-in request can only ever read or write rows belonging to that
          user&apos;s own account, enforced by the database itself rather than by
          application code. Nobody else — including anyone using Elara — can read
          your conversations.
        </p>
      </LegalSection>

      <LegalSection heading="Deleting your data">
        <p>
          Settings → Account → Delete account removes your profile, your
          preferences, your conversations and every message in them, then deletes
          your sign-in. It cannot be undone. Deleting the account is the only
          action that removes your data from our systems; signing out does not.
        </p>
        <p>
          Conversation history is a preference you can change at any time without
          deleting your account.
        </p>
      </LegalSection>

      <LegalSection heading="Guest sessions">
        <p>
          A guest session has no email address and no password, so we cannot
          recover it or send anything to it. It works for the current session; it
          is not a permanent account.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
